# used https://github.com/GoogleCloudPlatform/solutions-build-multi-architecture-images-tutorial/blob/master/terraform/cloud-build/build-docker-image-trigger.yaml
# as a guide for the multiarch setup
# (from https://github.com/GoogleCloudPlatform/solutions-build-multi-architecture-images-tutorial)


steps:
  - id: 'initialize-qemu'
    name: 'gcr.io/cloud-builders/docker'
    args: [ 'run', '--privileged', 'linuxkit/binfmt:v0.8' ]

  - id: 'create-builder'
    name: 'gcr.io/cloud-builders/docker'
    args: [ 'buildx', 'create', '--name', 'mybuilder' ]

  - id: 'select-builder'
    name: 'gcr.io/cloud-builders/docker'
    args: [ 'buildx', 'use', 'mybuilder' ]

  - id: 'show-target-build-platforms'
    name: 'gcr.io/cloud-builders/docker'
    args: [ 'buildx', 'inspect', '--bootstrap' ]

  - name: 'gcr.io/cloud-builders/docker'
    args: [
      'buildx', 'build',
      '--progress', 'plain',
      '--push',
      #'--platform', 'linux/amd64',
      #'--platform', 'linux/arm64',
      '--platform', 'linux/amd64,linux/arm64',
      '--tag', 'us-central1-docker.pkg.dev/reflexions-ci-builder/$REPO_NAME/ci-builder:$BRANCH_NAME',

      '.'
    ]
options:
  env:
    - 'DOCKER_CLI_EXPERIMENTAL=enabled'

  # https://cloud.google.com/cloud-build/docs/api/reference/rest/v1/projects.builds#machinetype
  # unspecified, N1_HIGHCPU_8, N1_HIGHCPU_32, E2_HIGHCPU_8, E2_HIGHCPU_32
  #machineType: 'E2_HIGHCPU_8'

  pool:
    name: 'projects/reflexions-cubic/locations/us-central1/workerPools/e2-highmem-4'

timeout: 2400s
